name: test job

on: push

jobs: 
    myfirstjob:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: welcome message
          run: |
            echo "testing first action"
            echo $(date)
            cat Dockerfile
            ls -lrta

        # - name: time print
        #   run: echo $(date)
        # - name: list files
        #   run: cat Dockerfile



 