name: test job

on: push

jobs: 
    myfirstjob:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "testing first action"
        - name: time print
          run: echo $(date)



 